add admin cmd, backup cmd, and relative config. Update some code struct
pando-project/pando pull request #120
Opened 2022-03-15 10:53 UTC by sssion

2022-03-15 23:24 UTC, sugarforever commented on cmd/client/command/admin/admin.go
> +		Short: "admin the Pando",
Short: 可以改为"Pando administration"

2022-03-15 23:28 UTC, sugarforever commented on cmd/client/command/admin/backup.go
> +	if bq.StartCid == "" || bq.EndCid == "" {
这里是否可以允许EndCid为空？在EndCid为空的情况下，Pando程序内部可以用StartCid的值来设置EndCid，以确保遍历到起点

2022-03-15 23:30 UTC, sugarforever commented on pkg/api/v1/admin/backup.go
> +					logger.Errorf("failed to clean the car file, err: %v", err)
这里的错误日志里是否能确保清理失败的car文件的路径？

2022-03-15 23:31 UTC, sugarforever commented on pkg/api/v1/admin/backup.go
> +			logger.Errorf("failed to generate car file, err:%v", err)
这里的错误日志里把start, end, filepath这些信息都记录进去吧

2022-03-15 23:32 UTC, sugarforever commented on pkg/api/v1/admin/backup.go
> +				logger.Errorf("failed to back up car to estuary, err:%v", err)
把filePath也记入错误日志吧，比如：
"failed to back up car file ${filePath} to estuary, err:%v"

2022-03-15 23:33 UTC, sugarforever commented on pkg/api/v1/admin/backup.go
> +			ctx.JSON(http.StatusOK, types.NewOKResponse(fmt.Sprintf("back up successfully! Estuary id: %d", estId), ""))
把filePath也记入响应消息吧，比如：
"back up successfully! CAR path: %s, Estuary id: %d"

2022-03-15 23:36 UTC, sugarforever reviewed
1. EndCid是否可以不提供？
2. 日志信息完善

2022-03-16 07:45 UTC, bsjohnson01 requested changes

2022-03-16 07:45 UTC, bsjohnson01 commented on cmd/client/command/admin/backup.go
> +			if backupRequest.IsForce == true {
这里可以用map实现，减少冗余代码

2022-03-16 07:45 UTC, bsjohnson01 commented on pkg/api/router.go
> +	adminRouter.Use(middleware.WithAPIDoc())
admin server有api文档吗？如果有的话，要新建一个文档中间件，这里的api文档中间件读取的是pando api接口的swagger文档

2022-03-16 07:45 UTC, bsjohnson01 commented on cmd/client/command/admin/backup.go
> +			if backupRequest.IsForce == true {
例如：
```suggestion
			trueTable := map[bool]string{true: "1", false: "0"}
			req := api.Client.R().
				SetQueryParam("start", backupRequest.StartCid).
				SetQueryParam("end", backupRequest.EndCid).
				SetQueryParam("force", trueTable[backupRequest.IsForce])
			if backupRequest.Provider != "" {
				req.SetQueryParam("provider", backupRequest.Provider)
			}
```

2022-03-16 07:45 UTC, bsjohnson01 commented on pkg/api/v1/admin/backup.go
> +	}
这里如果要利用golang的bool类型零值为false的特性的话，只要判断force=="1"就行了，因为其他情况都是false，那么客户端那里传参的时候也只要传"1"或者"true"就行了，就没有必要传"0"

2022-03-16 13:05 UTC, bsjohnson01 approved these changes

2022-03-16 13:05 UTC, merged