update the http status code in meta http server
pando-project/pando pull request #29
Opened 2021-11-25 09:17 UTC by sssion

2021-12-02 08:08 UTC, bsjohnson01 requested changes
As @sugarforever  said a few days ago, some of these server errors should be breakdown into several different types of errors

2021-12-06 12:03 UTC, sugarforever requested changes

2021-12-06 12:03 UTC, sugarforever commented on server/metadata/http/handler.go
>  	ss, err := h.metaHandler.StateTree.GetSnapShot(ssCid)
这里我们需要确认相关实现。GetSnapshot的实现依赖于IpldStore.Get。需要确认Get的实现如何处理找不到的情况。比如一个CID在store里没找到，是返回空还是以error来表示。如果ssCid在store里没找到，返回的是nil的ss和err。那么这里的响应码就应该做相应的调整。
```
if ss == nil:
    if err == nil:
        404
    else:
        500
```

2021-12-06 12:03 UTC, sugarforever commented on server/metadata/http/handler.go
>  	ss, err := h.metaHandler.StateTree.GetSnapShotByHeight(ssHeight)
与上面的情况类似^^

2021-12-06 12:04 UTC, sugarforever commented on server/metadata/http/handler.go
>  	ss, err := h.metaHandler.StateTree.GetSnapShot(ssCid)
https://github.com/kenlabs/pando/pull/34 看到这个处理逻辑了。

2021-12-06 12:05 UTC, merged