Feat/hamt snapshot
pando-project/pando pull request #3
Opened 2021-11-09 14:47 UTC by sssion

2021-11-09 15:58 UTC, sugarforever requested changes

2021-11-09 15:58 UTC, sugarforever commented on command/daemon.go
> +	//err := logging.SetLogLevel("*", "info")
这里的注释可以清理掉。

2021-11-09 15:58 UTC, sugarforever commented on command/daemon.go
> +	if err != nil {
这里的if逻辑有重复

2021-11-09 15:58 UTC, sugarforever commented on command/flags.go
> +		//Usage:    "GraphSync HTTP API listen address",
如果不需要描述信息，这里的注释也可以删掉了

2021-11-09 15:58 UTC, sugarforever commented on command/snapshot.go
> +	Name:   "cidlist",
这里的几个属性值似乎和list snapshots功能不匹配

2021-11-09 15:58 UTC, sugarforever commented on legs/core.go
> +			log.Errorf("Error persisting latest sync: %s", err)
这里putLatestSync出错后，是否需要继续for循环剩余的操作？

2021-11-09 15:58 UTC, sugarforever commented on legs/core.go
> +		v, e := l.BS.Get(c)
188 - 192行是为了调试加的吧？这里可以删除

2021-11-09 15:58 UTC, sugarforever commented on legs/link_system.go
> +//func dsKey(k string) datastore.Key {
不需要的代码可以删除

2021-11-09 15:58 UTC, sugarforever commented on legs/link_system.go
> +	//lsys.StorageReadOpener = func(_ ipld.LinkContext, lnk ipld.Link) (io.Reader, error) {
这部分代码也可以删除

2021-11-09 15:58 UTC, sugarforever commented on legs/link_system.go
> +		//// Decode entries into an IPLD node
这部分也可以删除

2021-11-09 15:58 UTC, sugarforever commented on metadata/metadata_manage.go
> +	for _, c := range cidlist {
这部分调试代码还需要吗？

2021-11-09 15:58 UTC, sugarforever commented on server/graph_sync/http/server.go
> +//type logEcapsulator struct {
这块注释掉的代码也可以删了吧

2021-11-09 15:58 UTC, sugarforever commented on server/metadata/http/handler.go
> +	//id, err := getCid(r)
注释代码可以删除

2021-11-09 15:59 UTC, sssion commented on command/snapshot.go
> +	Name:   "cidlist",
之前想做snapshot的daemon command，后面没做，我删了吧

2021-11-09 16:01 UTC, sssion commented on legs/core.go
> +			log.Errorf("Error persisting latest sync: %s", err)
可能会部分重复获取，但应该为非致命错误，这里是照搬的storetheindex

2021-11-09 16:02 UTC, sssion commented on metadata/metadata_manage.go
> +	for _, c := range cidlist {
这里就是导出car, 暂时没使用这个函数

2021-11-10 08:06 UTC, bsjohnson01 reviewed
metadata接口和graphql接口建议写几个简单的测试

2021-11-10 08:06 UTC, bsjohnson01 commented on config/addresses.go
> +	MetaData string
一个小问题，现在的初始化逻辑是检查config文件是否存在，如果存在就返回err，不过提示的是configuration file already exists，返回码是0，那么新的默认配置例如defaultMetaData就不会被应用，容易误导用户配置文件是ok的，但跑daemon的时候由于metadata服务的监听地址没有配置，是空的，会报错。这不是一个bug，可以作为用户体验提升的需求放到之后的版本

2021-11-10 08:45 UTC, sssion commented on config/addresses.go
> +	MetaData string
是的，一个逻辑问题。如果版本升级，config发生变动，可能要删了再出实话，没有迁移操作。这个后面改吧

2021-11-10 09:48 UTC, sssion commented
> metadata接口和graphsync接口建议写几个简单的测试

已添加

2021-11-10 12:26 UTC, sugarforever approved these changes

2021-11-10 12:27 UTC, merged