Feat/pando 19
pando-project/pando pull request #33
Opened 2021-12-02 06:54 UTC by sssion

update ut to convey and gomonkey framework

2021-12-02 07:59 UTC, bsjohnson01 requested changes

2021-12-02 07:59 UTC, bsjohnson01 commented on api/v0/admin/model/register_request_test.go
> +		So(err, ShouldBeNil)
I think the data should be read then verified if it equals to the args you just passed into the request-maker

2021-12-02 07:59 UTC, bsjohnson01 commented on api/v0/admin/model/register_request_test.go
> +		// register again
What is the purpose of re-registering here?

2021-12-02 07:59 UTC, bsjohnson01 commented on api/v0/admin/model/register_request_test.go
> +			_, err = MakeRegisterRequest(peerID, privKey, []string{}, account)
Maybe it's necessary to ensure the returned data should be nil if a non-nil err returned

2021-12-02 07:59 UTC, bsjohnson01 commented on config/identity_test.go
> +		identity, err := CreateIdentity(io.Discard)
To test the CreateIdentity function, you may compare the identity which is the actual output of this function with your expect output

2021-12-06 09:00 UTC, sssion commented on api/v0/admin/model/register_request_test.go
> +		So(err, ShouldBeNil)
返回的是一个[]bytes,  我如果加以判断的话可能就是 判断 他生成的[]byte是否等于事先用他生成的[]byte

2021-12-06 09:01 UTC, sssion commented on api/v0/admin/model/register_request_test.go
> +		// register again
不应该有error，  只要timestamp正常

2021-12-06 09:03 UTC, sssion commented on config/identity_test.go
> +		identity, err := CreateIdentity(io.Discard)
这个func 生成random....

2021-12-08 10:12 UTC, merged